# These are supported funding model platforms

github: vedicscriptures
patreon: ptprashanttripathi
open_collective: ptprashanttripathi
ko_fi: ptprashanttripathi
custom: ["https://www.paypal.me/ptprashanttripathi"]
