# Site settings
lang: sa
title: Bhagavad Gita Quote API
description: Bhagavad Gita Quote API for free to all
url: https://docs.bhagavadgitaapi.in
twitter_username: bhagavadgitaapi
github_username:  vedicscriptures
meta:
  keywords: Bhagavad Gita API,vedic, vedic,script, programming language, sanskrit, ptprashanttripathi, Pt. Prashant Tripathi
  author: Pt. Prashant Tripathi
readme_index:
  with_frontmatter: true
